language: php

sudo: false

env:
    global:
        - COMPOSER_NO_INTERACTION="1"

install:
    - composer install

matrix:
    include:
        -   php: 7.0
            env: COMPOSER_ARGS=""
        -   php: 7.1
            env: COMPOSER_ARGS=""
        -   php: 7.2
            env: COMPOSER_ARGS=""

        -   php: 7.0
            env: COMPOSER_ARGS="--prefer-lowest"
        -   php: 7.1
            env: COMPOSER_ARGS="--prefer-lowest"
        -   php: 7.2
            env: COMPOSER_ARGS="--prefer-lowest"

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - phpenv config-rm xdebug.ini || true
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist
